[package]
name = "hack_template"
version = "0.1.0"


[dependencies]

pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", rev = "cf9c4cc" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "162bed1" }
starknet = "=2.9.2"


[[target.starknet-contract]]

# Enable Sierra codegen.
sierra = true

# Enable CASM codegen.
casm = true

# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = true

allowed-libfuncs-list.name = "audited"
